### PR TITLE
1.Project task assigment for my react capstone project

### PR DESCRIPTION
**Pull request by misikir21**
1. Follos the template provider for React kanban project
2. I am working solo on this projcet

### CODE REVIEW

**Review by zeff96 — COMMENTED** [review]
## STATUS: INVALID CODE REVIEW 🛑 🛑 
Hi @misikir21, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that lacks contribution from other team members since this is a group project. Kindly liaise with student success if at all you have no other parts and attach screenshot of email approval from student success that shows you are allowed to work on this project solo

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by misikir21** [comment]
solo
i am working solo

**Review by nedjwab — APPROVED** [review]
# 🟢 Project Approved! 🏆

## Hi  @misikir21                  👋

Your project is complete! ✔️✔  🏁

Your code was very professional 💯

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉

 
## Highlights 🌟

- ✔️ Descriptive commmit messsages
- ✔️ Descriptive PR description
- ✔️ No linter Errors


- The code is top-notch! 💯 and have a huge potential.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by misikir21** [comment]
Allow space travellers to book rocket
-  Show the status of booked travel 
-  Booker profile card 
-  Available mission page
-  Rockets section displays a list of all available SpaceX rockets

**Pull request merged**
